### ISSUE TITLE
Scroll Navigation Adjustment

### ISSUE THREAD

**Issue by rcass** [cyu1188/Aloha-Apparel#6]
For the scroll nav, when I click on the different nav links it scrolls to an area but that some of the nav bar covers the part of the page we want to see.

![screen shot 2017-02-07 at 2 11 59 pm](https://cloud.githubusercontent.com/assets/5028555/22713985/6e8a665e-ed3f-11e6-85e2-adc6682f75a9.png)

^ For example I should see the heading above.

Looks like the offset of the scroll needs to be adjusted to accommodate the space the nav bar takes up.

**Comment by cyu1188** [comment]
resolved
